global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: golang
    metrics_path: /prometheus
    # localhost
    static_configs:
      - targets: ["host.docker.internal:8080"]
#    # production
#    static_configs:
#      - targets: [ "your_ip:8080" ]